### ISSUE TITLE
Not compatible with Java SDK V2

### ISSUE THREAD

**Issue by mngo87** [awslabs/amazon-sns-java-extended-client-lib#7]
I created a PR for this: https://github.com/awslabs/amazon-sns-java-extended-client-lib/pull/6

**Comment by aws-rizi** [comment]
Thanks. 
Will be checking the PR.

**Comment by dorongold** [comment]
What is the status of this?
Is there a plan to support AWS SDK V2?

**Comment by lbenedetto** [comment]
Why is this still not merged? We can't upgrade to SDK v2 until this is taken care of...

**Comment by frehov** [comment]
this is now a blocker for us as well on projects where we're already on SDK V2

**Comment by frehov** [comment]
maybe @eddy-aws or @adam-aws could have a look since they reviewed the upgrade to sdk v2 in the payload offloading library

**Comment by jerrymj** [comment]
Could this be prioritized, please?

**Comment by starichkovva** [comment]
Why `com.amazonaws:amazon-sqs-java-extended-client-lib` is already migrated to AWS SDK v2, while this one still does not? 

We've been forced by AWS to migrate to its V2 to be able to use it with Java 17, but at the same time you still can't merge this PR for 2 years... How long we should wait?

**Comment by shih** [comment]
Apologies for the late reply, we have released new version 2.0.0 which is compatible with SDKV2.
